In [22]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [23]:
df = pd.read_csv("weatherHistory.csv")
df.head(5)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Formatted Date            96453 non-null  str
 1   Summary                   96453 non-null  str
 2   Precip Type               95936 non-null  str
 3   Temperature (C)           96453 non-null  float64
 4   Apparent Temperature (C)  96453 non-null  float64
 5   Humidity                  96453 non-null  float64
 6   Wind Speed (km/h)         96453 non-null  float64
 7   Wind Bearing (degrees)    96453 non-null  float64
 8   Visibility (km)           96453 non-null  float64
 9   Loud Cover                96453 non-null  float64
 10  Pressure (millibars)      96453 non-null  float64
 11  Daily Summary             96453 non-null  str
dtypes: float64(8), str(4)
memory usage: 8.8 MB

ENCODING CATEGORICAL DATA:

USING NUMERICAL ORDER MIGHT MISLEAD THE MACHINE LEARNING MODEL TO THINK THE LABELS/NAMES INFLUENCE THE OUTCOME (MISINTERPRETED CORELATION)

ONE HOT ENCODING:

CONVERTS EACH INTO DIFFERENT COLUMNS AND USES VECTORS SUCH AS [1,0,0], [0,1,0] AND [0,0,1]. SO NOW THERE IS NO NUMERICAL ORDER IN THE DATA AND ONLY 0s AND 1s ARE USED. (USEFUL WHEN CATEGORICAL VARIABLES)

In [25]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

features_to_drop = ['Formatted Date', 'Temperature (C)', 'Daily Summary']
X_df = df.drop(columns=features_to_drop)
X = X_df.values
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse_output=False), [0, 1])], remainder='passthrough')
X_encoded = np.array(ct.fit_transform(X))

In [27]:
print(X_encoded)

[[0.0 0.0 0.0 ... 15.826300000000002 0.0 1015.13]
 [0.0 0.0 0.0 ... 15.826300000000002 0.0 1015.63]
 [0.0 0.0 0.0 ... 14.9569 0.0 1015.94]
 ...
 [0.0 0.0 0.0 ... 16.1 0.0 1015.66]
 [0.0 0.0 0.0 ... 16.1 0.0 1015.95]
 [0.0 0.0 0.0 ... 15.520400000000002 0.0 1016.16]]

In [28]:
df.head(5)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

Normalization (Min-Max Scaling):

Squashes all your numbers so they fit exactly between 0.0 and 1.0. It does this by looking at the strict minimum and maximum values of your column. It is highly sensitive to extreme outliers.

Standardization (Z-Score Scaling):

Shifts your data so the average (mean) is 0, and most of your data falls between -3 and 3. It doesn't put strict limits on the data, which makes it much more robust if your weather data has a crazy outlier (like an abnormally low-pressure storm).

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, Y_train, Y_test = train_test_split(X_encoded, Y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [31]:
pd.DataFrame(X_train_scaled).to_csv('X_train.csv', index=False)
pd.DataFrame(X_test_scaled).to_csv('X_test.csv', index=False)
pd.DataFrame(Y_train).to_csv('y_train.csv', index=False)
pd.DataFrame(Y_test).to_csv('y_test.csv', index=False)